### ISSUE TITLE
new search feature autocomplete using github cookies?

### ISSUE THREAD

**Issue by CicerosPatience** [dellsystem/new-socialist#21]
Hey just wanted to let you know that it looks like the search is pulling some default autocomplete results from github search history cookies (see image below)? I know its still a basic implementation, just wanted to make sure you were aware.

Great site btw 👍 Would love to contribute if I can find some time in the future.

![image](https://user-images.githubusercontent.com/19209643/41944570-455f0dae-79a0-11e8-9f53-ede3a2d597aa.png)

**Comment by dellsystem** [comment]
seems like that's just your browser's autocomplete feature. i'll disable autocompletion, thanks

**Comment by CicerosPatience** [comment]
Ah yeah, good point. Hadn't considered that 👍
